### ISSUE TITLE
TypeError: index.js:35: undefined is not a function

### ISSUE THREAD

**Issue by superKalo** [nathanmac/laravel-elixir-imagemin#13]
Hello,

I am using: Laravel 5.1 and Elixir 2.3.13. I am getting an error when I run the imagemin task. I am using the same config as the last example (all of the other examples gives me the same error as well, even if I do not pass any params):

``` javascript
elixir(function(mix) {
    mix.imagemin(
        "./resources/assets/img",
        "public/img",
        { optimizationLevel: 3, progressive: true, interlaced: true }
    );
});
```

And it fails:

```
/Users/superkalo/Sites/one-studio/node_modules/laravel-elixir-imagemin/index.js:35
    new elixir.Task('imagemin', function () {
              ^
TypeError: undefined is not a function
    at Object.imagemin (/Users/superkalo/Sites/one-studio/node_modules/laravel-elixir-imagemin/index.js:35:15)
    at /Users/superkalo/Sites/one-studio/gulpfile.js:93:10
    at Elixir (/Users/superkalo/Sites/one-studio/node_modules/laravel-elixir/index.js:3:5)
    at Object.<anonymous> (/Users/superkalo/Sites/one-studio/gulpfile.js:25:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Any suggestions why?
Thanks in Advance!

**Comment by superKalo** [comment]
Hey, I [updated to Elixir 3.0](https://github.com/laravel/elixir/releases/tag/3.0.0), which resolved the issue :)

**Comment by nicklee1990** [comment]
has this been released? I'm still seeing the issue

**Comment by charl-kruger** [comment]
@nicklee1990 In your project's root package.json file, update the Laravel Elixir version number to ^3.0.0, and run npm update.

Check the documentation - https://github.com/laravel/elixir/releases/tag/3.0.0
