### ISSUE TITLE
Cannot find module 'laravel-elixir-imagemin'

### ISSUE THREAD

**Issue by rbruhn** [nathanmac/laravel-elixir-imagemin#20]
Decided to try this on a Laravel 5.2 project. I'm getting the following error:

```
Error: Cannot find module 'laravel-elixir-imagemin'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Users\Robert\MyWebs\Sites\biospex\gulpfile.js:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Right now, my gulp file is stripped down to the most basic code:

```
var elixir = require('laravel-elixir');
require('laravel-elixir-imagemin');
```

Any ideas?

**Comment by rbruhn** [comment]
Nvm.... it was my fault. The installation didn't work right.
